﻿/*eslint unicode-bom: ["error", "always"]*/
const madridMun = [
  {"codpro":"28","codmun":"001","name":"Acebeda, La","label":"Acebeda, La","value":"Acebeda, La"},
  {"codpro":"28","codmun":"002","name":"Ajalvir","label":"Ajalvir","value":"Ajalvir"},
  {"codpro":"28","codmun":"003","name":"Alameda del Valle","label":"Alameda del Valle","value":"Alameda del Valle"},
  {"codpro":"28","codmun":"004","name":"�lamo, El","label":"Álamo, El","value":"Álamo, El"},
  {"codpro":"28","codmun":"005","name":"Alcal� de Henares","label":"Alcalá de Henares","value":"Alcalá de Henares"},
  {"codpro":"28","codmun":"006","name":"Alcobendas","label":"Alcobendas","value":"Alcobendas"},
  {"codpro":"28","codmun":"007","name":"Alcorc�n","label":"Alcorcón","value":"Alcorcón"},
  {"codpro":"28","codmun":"008","name":"Aldea del Fresno","label":"Aldea del Fresno","value":"Aldea del Fresno"},
  {"codpro":"28","codmun":"009","name":"Algete","label":"Algete","value":"Algete"},
  {"codpro":"28","codmun":"010","name":"Alpedrete","label":"Alpedrete","value":"Alpedrete"},
  {"codpro":"28","codmun":"011","name":"Ambite","label":"Ambite","value":"Ambite"},
  {"codpro":"28","codmun":"012","name":"Anchuelo","label":"Anchuelo","value":"Anchuelo"},
  {"codpro":"28","codmun":"013","name":"Aranjuez","label":"Aranjuez","value":"Aranjuez"},
  {"codpro":"28","codmun":"014","name":"Arganda del Rey","label":"Arganda del Rey","value":"Arganda del Rey"},
  {"codpro":"28","codmun":"015","name":"Arroyomolinos","label":"Arroyomolinos","value":"Arroyomolinos"},
  {"codpro":"28","codmun":"016","name":"Atazar, El","label":"Atazar, El","value":"Atazar, El"},
  {"codpro":"28","codmun":"017","name":"Batres","label":"Batres","value":"Batres"},
  {"codpro":"28","codmun":"018","name":"Becerril de la Sierra","label":"Becerril de la Sierra","value":"Becerril de la Sierra"},
  {"codpro":"28","codmun":"019","name":"Belmonte de Tajo","label":"Belmonte de Tajo","value":"Belmonte de Tajo"},
  {"codpro":"28","codmun":"021","name":"Berrueco, El","label":"Berrueco, El","value":"Berrueco, El"},
  {"codpro":"28","codmun":"020","name":"Berzosa del Lozoya","label":"Berzosa del Lozoya","value":"Berzosa del Lozoya"},
  {"codpro":"28","codmun":"022","name":"Boadilla del Monte","label":"Boadilla del Monte","value":"Boadilla del Monte"},
  {"codpro":"28","codmun":"023","name":"Boalo, El","label":"Boalo, El","value":"Boalo, El"},
  {"codpro":"28","codmun":"024","name":"Braojos","label":"Braojos","value":"Braojos"},
  {"codpro":"28","codmun":"025","name":"Brea de Tajo","label":"Brea de Tajo","value":"Brea de Tajo"},
  {"codpro":"28","codmun":"026","name":"Brunete","label":"Brunete","value":"Brunete"},
  {"codpro":"28","codmun":"027","name":"Buitrago del Lozoya","label":"Buitrago del Lozoya","value":"Buitrago del Lozoya"},
  {"codpro":"28","codmun":"028","name":"Bustarviejo","label":"Bustarviejo","value":"Bustarviejo"},
  {"codpro":"28","codmun":"029","name":"Cabanillas de la Sierra","label":"Cabanillas de la Sierra","value":"Cabanillas de la Sierra"},
  {"codpro":"28","codmun":"030","name":"Cabrera, La","label":"Cabrera, La","value":"Cabrera, La"},
  {"codpro":"28","codmun":"031","name":"Cadalso de los Vidrios","label":"Cadalso de los Vidrios","value":"Cadalso de los Vidrios"},
  {"codpro":"28","codmun":"032","name":"Camarma de Esteruelas","label":"Camarma de Esteruelas","value":"Camarma de Esteruelas"},
  {"codpro":"28","codmun":"033","name":"Campo Real","label":"Campo Real","value":"Campo Real"},
  {"codpro":"28","codmun":"034","name":"Canencia","label":"Canencia","value":"Canencia"},
  {"codpro":"28","codmun":"035","name":"Caraba�a","label":"Carabaña","value":"Carabaña"},
  {"codpro":"28","codmun":"036","name":"Casarrubuelos","label":"Casarrubuelos","value":"Casarrubuelos"},
  {"codpro":"28","codmun":"037","name":"Cenicientos","label":"Cenicientos","value":"Cenicientos"},
  {"codpro":"28","codmun":"038","name":"Cercedilla","label":"Cercedilla","value":"Cercedilla"},
  {"codpro":"28","codmun":"039","name":"Cervera de Buitrago","label":"Cervera de Buitrago","value":"Cervera de Buitrago"},
  {"codpro":"28","codmun":"051","name":"Chapiner�a","label":"Chapinería","value":"Chapinería"},
  {"codpro":"28","codmun":"052","name":"Chinch�n","label":"Chinchón","value":"Chinchón"},
  {"codpro":"28","codmun":"040","name":"Ciempozuelos","label":"Ciempozuelos","value":"Ciempozuelos"},
  {"codpro":"28","codmun":"041","name":"Cobe�a","label":"Cobeña","value":"Cobeña"},
  {"codpro":"28","codmun":"046","name":"Collado Mediano","label":"Collado Mediano","value":"Collado Mediano"},
  {"codpro":"28","codmun":"047","name":"Collado Villalba","label":"Collado Villalba","value":"Collado Villalba"},
  {"codpro":"28","codmun":"043","name":"Colmenar de Oreja","label":"Colmenar de Oreja","value":"Colmenar de Oreja"},
  {"codpro":"28","codmun":"042","name":"Colmenar del Arroyo","label":"Colmenar del Arroyo","value":"Colmenar del Arroyo"},
  {"codpro":"28","codmun":"045","name":"Colmenar Viejo","label":"Colmenar Viejo","value":"Colmenar Viejo"},
  {"codpro":"28","codmun":"044","name":"Colmenarejo","label":"Colmenarejo","value":"Colmenarejo"},
  {"codpro":"28","codmun":"048","name":"Corpa","label":"Corpa","value":"Corpa"},
  {"codpro":"28","codmun":"049","name":"Coslada","label":"Coslada","value":"Coslada"},
  {"codpro":"28","codmun":"050","name":"Cubas de la Sagra","label":"Cubas de la Sagra","value":"Cubas de la Sagra"},
  {"codpro":"28","codmun":"053","name":"Daganzo de Arriba","label":"Daganzo de Arriba","value":"Daganzo de Arriba"},
  {"codpro":"28","codmun":"054","name":"Escorial, El","label":"Escorial, El","value":"Escorial, El"},
  {"codpro":"28","codmun":"055","name":"Estremera","label":"Estremera","value":"Estremera"},
  {"codpro":"28","codmun":"056","name":"Fresnedillas de la Oliva","label":"Fresnedillas de la Oliva","value":"Fresnedillas de la Oliva"},
  {"codpro":"28","codmun":"057","name":"Fresno de Torote","label":"Fresno de Torote","value":"Fresno de Torote"},
  {"codpro":"28","codmun":"058","name":"Fuenlabrada","label":"Fuenlabrada","value":"Fuenlabrada"},
  {"codpro":"28","codmun":"059","name":"Fuente el Saz de Jarama","label":"Fuente el Saz de Jarama","value":"Fuente el Saz de Jarama"},
  {"codpro":"28","codmun":"060","name":"Fuentidue�a de Tajo","label":"Fuentidueña de Tajo","value":"Fuentidueña de Tajo"},
  {"codpro":"28","codmun":"061","name":"Galapagar","label":"Galapagar","value":"Galapagar"},
  {"codpro":"28","codmun":"062","name":"Garganta de los Montes","label":"Garganta de los Montes","value":"Garganta de los Montes"},
  {"codpro":"28","codmun":"063","name":"Gargantilla del Lozoya y Pinilla de Buitrago","label":"Gargantilla del Lozoya y Pinilla de Buitrago","value":"Gargantilla del Lozoya y Pinilla de Buitrago"},
  {"codpro":"28","codmun":"064","name":"Gascones","label":"Gascones","value":"Gascones"},
  {"codpro":"28","codmun":"065","name":"Getafe","label":"Getafe","value":"Getafe"},
  {"codpro":"28","codmun":"066","name":"Gri��n","label":"Griñón","value":"Griñón"},
  {"codpro":"28","codmun":"067","name":"Guadalix de la Sierra","label":"Guadalix de la Sierra","value":"Guadalix de la Sierra"},
  {"codpro":"28","codmun":"068","name":"Guadarrama","label":"Guadarrama","value":"Guadarrama"},
  {"codpro":"28","codmun":"069","name":"Hiruela, La","label":"Hiruela, La","value":"Hiruela, La"},
  {"codpro":"28","codmun":"070","name":"Horcajo de la Sierra-Aoslos","label":"Horcajo de la Sierra-Aoslos","value":"Horcajo de la Sierra-Aoslos"},
  {"codpro":"28","codmun":"071","name":"Horcajuelo de la Sierra","label":"Horcajuelo de la Sierra","value":"Horcajuelo de la Sierra"},
  {"codpro":"28","codmun":"072","name":"Hoyo de Manzanares","label":"Hoyo de Manzanares","value":"Hoyo de Manzanares"},
  {"codpro":"28","codmun":"073","name":"Humanes de Madrid","label":"Humanes de Madrid","value":"Humanes de Madrid"},
  {"codpro":"28","codmun":"074","name":"Legan�s","label":"Leganés","value":"Leganés"},
  {"codpro":"28","codmun":"075","name":"Loeches","label":"Loeches","value":"Loeches"},
  {"codpro":"28","codmun":"076","name":"Lozoya","label":"Lozoya","value":"Lozoya"},
  {"codpro":"28","codmun":"901","name":"Lozoyuela-Navas-Sieteiglesias","label":"Lozoyuela-Navas-Sieteiglesias","value":"Lozoyuela-Navas-Sieteiglesias"},
  {"codpro":"28","codmun":"078","name":"Madarcos","label":"Madarcos","value":"Madarcos"},
  {"codpro":"28","codmun":"079","name":"Madrid","label":"Madrid","value":"Madrid"},
  {"codpro":"28","codmun":"080","name":"Majadahonda","label":"Majadahonda","value":"Majadahonda"},
  {"codpro":"28","codmun":"082","name":"Manzanares el Real","label":"Manzanares el Real","value":"Manzanares el Real"},
  {"codpro":"28","codmun":"083","name":"Meco","label":"Meco","value":"Meco"},
  {"codpro":"28","codmun":"084","name":"Mejorada del Campo","label":"Mejorada del Campo","value":"Mejorada del Campo"},
  {"codpro":"28","codmun":"085","name":"Miraflores de la Sierra","label":"Miraflores de la Sierra","value":"Miraflores de la Sierra"},
  {"codpro":"28","codmun":"086","name":"Molar, El","label":"Molar, El","value":"Molar, El"},
  {"codpro":"28","codmun":"087","name":"Molinos, Los","label":"Molinos, Los","value":"Molinos, Los"},
  {"codpro":"28","codmun":"088","name":"Montejo de la Sierra","label":"Montejo de la Sierra","value":"Montejo de la Sierra"},
  {"codpro":"28","codmun":"089","name":"Moraleja de Enmedio","label":"Moraleja de Enmedio","value":"Moraleja de Enmedio"},
  {"codpro":"28","codmun":"090","name":"Moralzarzal","label":"Moralzarzal","value":"Moralzarzal"},
  {"codpro":"28","codmun":"091","name":"Morata de Taju�a","label":"Morata de Tajuña","value":"Morata de Tajuña"},
  {"codpro":"28","codmun":"092","name":"M�stoles","label":"Móstoles","value":"Móstoles"},
  {"codpro":"28","codmun":"093","name":"Navacerrada","label":"Navacerrada","value":"Navacerrada"},
  {"codpro":"28","codmun":"094","name":"Navalafuente","label":"Navalafuente","value":"Navalafuente"},
  {"codpro":"28","codmun":"095","name":"Navalagamella","label":"Navalagamella","value":"Navalagamella"},
  {"codpro":"28","codmun":"096","name":"Navalcarnero","label":"Navalcarnero","value":"Navalcarnero"},
  {"codpro":"28","codmun":"101","name":"Olmeda de las Fuentes","label":"Olmeda de las Fuentes","value":"Olmeda de las Fuentes"},
  {"codpro":"28","codmun":"104","name":"Paracuellos de Jarama","label":"Paracuellos de Jarama","value":"Paracuellos de Jarama"},
  {"codpro":"28","codmun":"106","name":"Parla","label":"Parla","value":"Parla"},
  {"codpro":"28","codmun":"107","name":"Patones","label":"Patones","value":"Patones"},
  {"codpro":"28","codmun":"108","name":"Pedrezuela","label":"Pedrezuela","value":"Pedrezuela"},
  {"codpro":"28","codmun":"109","name":"Pelayos de la Presa","label":"Pelayos de la Presa","value":"Pelayos de la Presa"},
  {"codpro":"28","codmun":"110","name":"Perales de Taju�a","label":"Perales de Tajuña","value":"Perales de Tajuña"},
  {"codpro":"28","codmun":"111","name":"Pezuela de las Torres","label":"Pezuela de las Torres","value":"Pezuela de las Torres"},
  {"codpro":"28","codmun":"112","name":"Pinilla del Valle","label":"Pinilla del Valle","value":"Pinilla del Valle"},
  {"codpro":"28","codmun":"113","name":"Pinto","label":"Pinto","value":"Pinto"},
  {"codpro":"28","codmun":"115","name":"Pozuelo de Alarc�n","label":"Pozuelo de Alarcón","value":"Pozuelo de Alarcón"},
  {"codpro":"28","codmun":"116","name":"Pozuelo del Rey","label":"Pozuelo del Rey","value":"Pozuelo del Rey"},
  {"codpro":"28","codmun":"118","name":"Puebla de la Sierra","label":"Puebla de la Sierra","value":"Puebla de la Sierra"},
  {"codpro":"28","codmun":"902","name":"Puentes Viejas","label":"Puentes Viejas","value":"Puentes Viejas"},
  {"codpro":"28","codmun":"119","name":"Quijorna","label":"Quijorna","value":"Quijorna"},
  {"codpro":"28","codmun":"120","name":"Rascafr�a","label":"Rascafría","value":"Rascafría"},
  {"codpro":"28","codmun":"121","name":"Redue�a","label":"Redueña","value":"Redueña"},
  {"codpro":"28","codmun":"122","name":"Ribatejada","label":"Ribatejada","value":"Ribatejada"},
  {"codpro":"28","codmun":"123","name":"Rivas-Vaciamadrid","label":"Rivas-Vaciamadrid","value":"Rivas-Vaciamadrid"},
  {"codpro":"28","codmun":"124","name":"Robledillo de la Jara","label":"Robledillo de la Jara","value":"Robledillo de la Jara"},
  {"codpro":"28","codmun":"125","name":"Robledo de Chavela","label":"Robledo de Chavela","value":"Robledo de Chavela"},
  {"codpro":"28","codmun":"126","name":"Robregordo","label":"Robregordo","value":"Robregordo"},
  {"codpro":"28","codmun":"127","name":"Rozas de Madrid, Las","label":"Rozas de Madrid, Las","value":"Rozas de Madrid, Las"},
  {"codpro":"28","codmun":"128","name":"Rozas de Puerto Real","label":"Rozas de Puerto Real","value":"Rozas de Puerto Real"},
  {"codpro":"28","codmun":"129","name":"San Agust�n del Guadalix","label":"San Agustín del Guadalix","value":"San Agustín del Guadalix"},
  {"codpro":"28","codmun":"130","name":"San Fernando de Henares","label":"San Fernando de Henares","value":"San Fernando de Henares"},
  {"codpro":"28","codmun":"131","name":"San Lorenzo de El Escorial","label":"San Lorenzo de El Escorial","value":"San Lorenzo de El Escorial"},
  {"codpro":"28","codmun":"132","name":"San Mart�n de la Vega","label":"San Martín de la Vega","value":"San Martín de la Vega"},
  {"codpro":"28","codmun":"133","name":"San Mart�n de Valdeiglesias","label":"San Martín de Valdeiglesias","value":"San Martín de Valdeiglesias"},
  {"codpro":"28","codmun":"134","name":"San Sebasti�n de los Reyes","label":"San Sebastián de los Reyes","value":"San Sebastián de los Reyes"},
  {"codpro":"28","codmun":"136","name":"Santorcaz","label":"Santorcaz","value":"Santorcaz"},
  {"codpro":"28","codmun":"137","name":"Santos de la Humosa, Los","label":"Santos de la Humosa, Los","value":"Santos de la Humosa, Los"},
  {"codpro":"28","codmun":"138","name":"Serna del Monte, La","label":"Serna del Monte, La","value":"Serna del Monte, La"},
  {"codpro":"28","codmun":"140","name":"Serranillos del Valle","label":"Serranillos del Valle","value":"Serranillos del Valle"},
  {"codpro":"28","codmun":"141","name":"Sevilla la Nueva","label":"Sevilla la Nueva","value":"Sevilla la Nueva"},
  {"codpro":"28","codmun":"143","name":"Somosierra","label":"Somosierra","value":"Somosierra"},
  {"codpro":"28","codmun":"144","name":"Soto del Real","label":"Soto del Real","value":"Soto del Real"},
  {"codpro":"28","codmun":"145","name":"Talamanca de Jarama","label":"Talamanca de Jarama","value":"Talamanca de Jarama"},
  {"codpro":"28","codmun":"146","name":"Tielmes","label":"Tielmes","value":"Tielmes"},
  {"codpro":"28","codmun":"147","name":"Titulcia","label":"Titulcia","value":"Titulcia"},
  {"codpro":"28","codmun":"148","name":"Torrej�n de Ardoz","label":"Torrejón de Ardoz","value":"Torrejón de Ardoz"},
  {"codpro":"28","codmun":"151","name":"Torrelaguna","label":"Torrelaguna","value":"Torrelaguna"},
  {"codpro":"28","codmun":"152","name":"Torrelodones","label":"Torrelodones","value":"Torrelodones"},
  {"codpro":"28","codmun":"153","name":"Torremocha de Jarama","label":"Torremocha de Jarama","value":"Torremocha de Jarama"},
  {"codpro":"28","codmun":"154","name":"Torres de la Alameda","label":"Torres de la Alameda","value":"Torres de la Alameda"},
  {"codpro":"28","codmun":"903","name":"Tres Cantos","label":"Tres Cantos","value":"Tres Cantos"},
  {"codpro":"28","codmun":"155","name":"Valdaracete","label":"Valdaracete","value":"Valdaracete"},
  {"codpro":"28","codmun":"156","name":"Valdeavero","label":"Valdeavero","value":"Valdeavero"},
  {"codpro":"28","codmun":"157","name":"Valdelaguna","label":"Valdelaguna","value":"Valdelaguna"},
  {"codpro":"28","codmun":"158","name":"Valdemanco","label":"Valdemanco","value":"Valdemanco"},
  {"codpro":"28","codmun":"159","name":"Valdemaqueda","label":"Valdemaqueda","value":"Valdemaqueda"},
  {"codpro":"28","codmun":"160","name":"Valdemorillo","label":"Valdemorillo","value":"Valdemorillo"},
  {"codpro":"28","codmun":"161","name":"Valdemoro","label":"Valdemoro","value":"Valdemoro"},
  {"codpro":"28","codmun":"162","name":"Valdeolmos-Alalpardo","label":"Valdeolmos-Alalpardo","value":"Valdeolmos-Alalpardo"},
  {"codpro":"28","codmun":"163","name":"Valdepi�lagos","label":"Valdepiélagos","value":"Valdepiélagos"},
  {"codpro":"28","codmun":"164","name":"Valdetorres de Jarama","label":"Valdetorres de Jarama","value":"Valdetorres de Jarama"},
  {"codpro":"28","codmun":"165","name":"Valdilecha","label":"Valdilecha","value":"Valdilecha"},
  {"codpro":"28","codmun":"167","name":"Velilla de San Antonio","label":"Velilla de San Antonio","value":"Velilla de San Antonio"},
  {"codpro":"28","codmun":"169","name":"Venturada","label":"Venturada","value":"Venturada"},
  {"codpro":"28","codmun":"171","name":"Villa del Prado","label":"Villa del Prado","value":"Villa del Prado"},
  {"codpro":"28","codmun":"170","name":"Villaconejos","label":"Villaconejos","value":"Villaconejos"},
  {"codpro":"28","codmun":"172","name":"Villalbilla","label":"Villalbilla","value":"Villalbilla"},
  {"codpro":"28","codmun":"173","name":"Villamanrique de Tajo","label":"Villamanrique de Tajo","value":"Villamanrique de Tajo"},
  {"codpro":"28","codmun":"174","name":"Villamanta","label":"Villamanta","value":"Villamanta"},
  {"codpro":"28","codmun":"175","name":"Villamantilla","label":"Villamantilla","value":"Villamantilla"},
  {"codpro":"28","codmun":"176","name":"Villanueva de la Ca�ada","label":"Villanueva de la Cañada","value":"Villanueva de la Cañada"},
  {"codpro":"28","codmun":"178","name":"Villanueva de Perales","label":"Villanueva de Perales","value":"Villanueva de Perales"},
  {"codpro":"28","codmun":"177","name":"Villanueva del Pardillo","label":"Villanueva del Pardillo","value":"Villanueva del Pardillo"},
  {"codpro":"28","codmun":"179","name":"Villar del Olmo","label":"Villar del Olmo","value":"Villar del Olmo"},
  {"codpro":"28","codmun":"181","name":"Villaviciosa de Od�n","label":"Villaviciosa de Odón","value":"Villaviciosa de Odón"},
  {"codpro":"28","codmun":"182","name":"Villavieja del Lozoya","label":"Villavieja del Lozoya","value":"Villavieja del Lozoya"},
  {"codpro":"28","codmun":"183","name":"Zarzalejo","label":"Zarzalejo","value":"Zarzalejo"}
  ];
export default madridMun;
